In [7]:
import torch
import operator

In [2]:
a = torch.randn(1, 3)
b = torch.randn(1, 3)

In [3]:
a

tensor([[-1.7927, -0.3369,  0.3498]])

In [4]:
b

tensor([[ 0.0322, -1.5324,  1.1886]])

In [10]:
torch.add(a,b)

tensor([[-1.7605, -1.8693,  1.5385]])

In [11]:
sample = tuple(map(operator.add, a, b))
sample

(tensor([-1.7605, -1.8693,  1.5385]),)

In [12]:
sample2 = tuple(ti/2 for ti in sample)
sample2

(tensor([-0.8803, -0.9346,  0.7692]),)

In [13]:
sample3 = torch.add(a,b)
torch.div(sample3, 2)

tensor([[-0.8803, -0.9346,  0.7692]])